### ISSUE TITLE
Feature Request: Custom CSS

### ISSUE THREAD

**Issue by kerim** [yhatt/marp#1]
Having been frustrated with Deckset development, I was very happy to discover this project. One thing that I find particularly frustrating about Deckset is the inability to edit the CSS layout myself. Would love to have that available in Marp.

**Comment by yhatt** [comment]
Thank you for finding Marp!
I'm sorry, Marp (under development) can't apply custom CSS created by user because the rules of HTML elements and CSS have possibility of changing. But I also think that the custom CSS feature makes your presentation creative!

Please wait until ready to fix the theme's specification! If that's alright you can try to [build your Marp](https://github.com/yhatt/marp#getting-started) with customized [theme CSS (by Sass)](https://github.com/yhatt/marp/blob/master/sass/themes/default.sass).

**Comment by will-hart** [comment]
Workaround posted here https://github.com/yhatt/marp/issues/39#issuecomment-239337082

**Comment by yhatt** [comment]
refs: #5
