### ISSUE TITLE
VS Code Plugin!!!

### ISSUE THREAD

**Issue by tsteele-ndsc** [yhatt/marp#118]
This would be nice as a VS Code plugin!!!

**Comment by jrappen** [comment]
@tsteele-ndsc 

* <https://marketplace.visualstudio.com/items?itemName=goessner.mdmath> should help
* please close this issue

**Comment by yhatt** [comment]
You don't have to close.

![sneak-peak](https://user-images.githubusercontent.com/3993388/46599695-f2584d80-cb22-11e8-8163-962967ca1951.gif)

**Comment by yhatt** [comment]
I've created **[@marp-team/marp-vscode](https://github.com/marp-team/marp-vscode)** repository to our team. Currently we have not yet released, but you can try this repository with *VSCode insider preview* if interested. Toggle preview by writing `marp: true` in front-matter.

![](https://raw.githubusercontent.com/marp-team/marp-vscode/master/screenshot.png)

VSCode has the same parser with Marp / Marpit (markdown-it), so you can even extend favorite syntaxes by another VSCode plugin.

**Comment by yhatt** [comment]
[Shipped out an initial release v0.0.1!!](https://marketplace.visualstudio.com/items?itemName=marp-team.marp-vscode) Currently, **it only supports [VS Code insiders](https://code.visualstudio.com/insiders/)** because of a difference the behavior for parsing front-matter.

Please track at **[marp-team/marp-vscode](https://github.com/marp-team/marp-vscode)** for future works and requests.
