### ISSUE TITLE
Support the mermaid

### ISSUE THREAD

**Issue by chih7** [yhatt/marp#125]
[mermaid](https://github.com/knsv/mermaid) can generate diagram and flowchart from text in a similar manner as markdown.

Some examples come from README:
<table>
    <tr><th>Code</th><th>Rendered diagram</th></tr>
    <tr>
        <td>
            <pre>
                <code>
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
                </code>
            </pre>
        </td>
        <td>
            <p align="center">
                <img src='http://www.sveido.com/mermaid/img/ex1.png' alt='Example 1'>
            </p>
        </td>
    </tr>
    <tr>
        <td>
            <pre>
                <code>
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts &lt;br/>prevail...
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
                </code>
            </pre>
        </td>
        <td>
            <img src='http://www.sveido.com/mermaid/img/seq1.png' alt='Example 2'>
        </td>
    </tr>
</table>

**Comment by ashutosh2411** [comment]
I would like to contribute to this issue. Is there a recent thread about the development of this particular feature?

**Comment by yhatt** [comment]
This issue is targeted to [Marp Next](https://github.com/marp-team/marp), so you should implement it on [marp-team/marp-core](https://github.com/marp-team/marp-core) if you want to start working. 

*yhatt/marp is already not maintained, so any pull requests for this repo would not merge.*

There is not a thread for this development because marp-core is not ready to accept contributing by lacking of the contributing guideline (only [a team guideline](https://github.com/marp-team/marp/blob/master/.github/CONTRIBUTING.md) is applied). However I think mermaid.js could support by changing the implementation of [`Marp.highlighter()`](https://github.com/marp-team/marp-core/blob/master/src/marp.ts#L99-L106).

**Comment by yhatt** [comment]
I had tried to implement better support of Mermaid to [Marp Core](https://github.com/marp-team/marp-core), but I have stopped work because it has several problems. We wait until the improvement of mermaid to support the non-browser environment.

I'll write down the working memos...

- The easiest way to use mermaid is using [markdown-it-mermaid](https://github.com/tylingsoft/markdown-it-mermaid) plugin. But it is not working without web context. [Marp Web](https://github.com/marp-team/marp-web) is converting Markdown within Web Worker for performance, so it does not work.

- Execute `mermaid.initialize()` in `Marp.ready()` is also working with conversion `<div class="mermaid">` in `highlighter()`. However, it has blinking chart in Marp Web's live preview.

- [Marp for VS Code](https://github.com/marp-team/marp-vscode) is supporting [Markdown Preview mermaid support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) experimentally. Sadly the example graph has the incorrect text size.

```markdown
---
marp: true
---

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```​
```

<img width="1038" alt="2019-02-07 18 58 14" src="https://user-images.githubusercontent.com/3993388/52403598-68d57e00-2b0a-11e9-9ab0-83fb5f56b6e4.png">

**Comment by mymmoonoa** [comment]
need support of mermaid...

**Comment by yhatt** [comment]
@mymmoonoa You can try to use mermaid.js directly via HTML as a workaround.

```markdown
# Mermaid

<div class="mermaid">
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
</div>

<!-- mermaid.js -->
<script src="https://unpkg.com/mermaid@8.1.0/dist/mermaid.min.js"></script>
<script>mermaid.initialize({startOnLoad:true});</script>
```
