### ISSUE TITLE
Issue from LaTeX Rendering

### ISSUE THREAD

**Issue by Jinwuk** [yhatt/marp#158]
I found that when I write out a Latex expression such that 
$x_i \overset{\mathbb{K}}{\rightarrow} x^{*}$,
Marp cannot redner the above expression. It renders only the Latex expression except '$'.
The above code is correct LaTeX expression. I verify it with a various Web based Latex engines as like "http://www.hostmath.com/". 
Can I expect this bug to be corrected as soon as possible?

Good Luck~

**Comment by will-hart** [comment]
Marp uses KaTeX for math rendering. `\overset` doesn't appear to be supported by katex

**Comment by yhatt** [comment]
Some functions are not worked in current Marp because [markdown-it-katex](https://github.com/waylonflinn/markdown-it-katex) bundled [the old version of KaTeX v0.6.0](https://github.com/waylonflinn/markdown-it-katex/blob/81b84a7d91d74a1ba3d4769b847a5bf1947256cb/package.json#L25).

In [Marp Next](https://github.com/marp-team/marp), we're keeping the latest version of KaTeX. (marp-team/marp-core#11) `\overset` is supported in KaTeX v0.8.0, so it would work on Marp Next. (Already you can try [CLI version](https://github.com/marp-team/marp-cli))

```
$x_i \overset{\mathbb{K}}{\rightarrow} x^{*}$
```

![screenshot_2018-10-08 marp](https://user-images.githubusercontent.com/3993388/46596941-13b43c00-cb19-11e8-9311-9437505d9d0f.png)
