### ISSUE TITLE
iOS Support 

### ISSUE THREAD

**Issue by pataiji** [yhatt/marp#180]
I want to use marp on a iPad.

**Comment by krokofant** [comment]
Since marp is based on Electron which supports Windows, Linux and macOS I doubt this is possible without a major overhaul to support a cordova-like build.

**Comment by dimkir** [comment]
Great question, but the short answer is NO. 

Electron (which in 2014 used to be called "atom-shell"), is basically bundle of Chromium + Nodejs + bit of magic.  When add Electron to your project, behind the scenes chromium and Nodejs is downloaded and added to your system. Whereas on Desktops those can run as "normal applications with full(ish) access to the system" (files, sockets, etc; no need for root/admin even), on mobile systems all apps are run "in a sandbox" (remember granting permissions to the app?). Thus porting Electron to mobile platforms seems highly unlikely. 

Another big problem you would hit on mobile devices - requirement for different UI language. Imagine running  Marp, VSCode or Atom editor on the phone? What size is the font supposed to be readable? How would you even access top menu? Thus this particular problem is even more serious than technical limitations. 

You can see original discussion of this problem here (not that they still call Electron - "atom-shell")
https://github.com/electron/electron/issues/5541


ps.  however if you're interested in  "in reverse" process: build an app in Ionic and then package it with Electron  [this seems to be possible](https://discuss.atom.io/t/electron-on-ios-android/18223/9)

**Comment by yhatt** [comment]
[Marp Next](https://github.com/marp-team/marp) is planning to migrate into web-based app. Even though it, iOS support had blocked by the critical rendering bug in WebKit. ([Bug 23113](https://bugs.webkit.org/show_bug.cgi?id=23113))

But recently this problem has been improved. We have created [polyfill for WebKit browser](https://github.com/marp-team/marpit-svg-polyfill) for our [Marpit framework](https://github.com/marp-team/marpit). By this polyfill, [the technology preview of Marp Web](https://5c2aa288e24f4a0008c5f14a--marp-web.netlify.com) can be worked in Safari now!

[![marp-on-ios](https://user-images.githubusercontent.com/3993388/50569518-5305c800-0daa-11e9-8fa4-08053c9b51cd.png)](https://5c2aa288e24f4a0008c5f14a--marp-web.netlify.com)

Because we made an outlook on iOS support, I've marked `Supports in Marp Next` tag to this issue.

**Comment by pataiji** [comment]
That's the best news in 2019!
