### ISSUE TITLE
Katex \begin{gathered} \end{gathered} environmnent

### ISSUE THREAD

**Issue by PhilWW** [yhatt/marp#199]
The Katex environment
$$
\begin{gathered}
   a=b \\ 
   e=b+c
\end{gathered}
$$
does not render although all other supported Katex environments  do (see https://khan.github.io/KaTeX/function-support.html#environments).

Am I doing something wrong? Marp says it typesets math using Katex. Can this be fixed easily? Thanks!

**Comment by yhatt** [comment]
Some functions are not worked in current Marp because [markdown-it-katex](https://github.com/waylonflinn/markdown-it-katex) bundled [the old version of KaTeX v0.6.0](https://github.com/waylonflinn/markdown-it-katex/blob/81b84a7d91d74a1ba3d4769b847a5bf1947256cb/package.json#L25).

In [Marp Next](https://github.com/marp-team/marp), we're keeping the latest version of KaTeX. (marp-team/marp-core#11) gathered environment is supported in KaTeX v0.8.0, so it would work on Marp Next. (Already you can try [CLI version](https://github.com/marp-team/marp-cli))

```
$$
\begin{gathered}
a=b \\
e=b+c
\end{gathered}
$$
```

![screenshot_2018-10-08 marp next](https://user-images.githubusercontent.com/3993388/46597039-73aae280-cb19-11e8-8302-07e5f490b4c5.png)

A similar case has reported in #158.
