### ISSUE TITLE
Support Preview Style: show Slide only

### ISSUE THREAD

**Issue by jefferyyuan** [yhatt/marp#223]
It would be great if marp can only show slides (not the markdown) when in preview mode.
- So we can just do the demo/presentation with marp without having to first convert it to ppt.

Thanks.

**Comment by xiaoliangastro** [comment]
Agree so much, need it madly.

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues. It is a duplicated issue with #13.

We must keep editor interface to support better live-preview, and essentially presentation mode is become the another feature.

However, it remains a low priority to develop because we are taking advantage of pdf. (Can make presentation with portable & no environment dependencies)
