### ISSUE TITLE
MarkdownPlus support?

### ISSUE THREAD

**Issue by fduxiao** [yhatt/marp#235]
Hey, would you consider adding the support of [MarkdownPlus](http://mdp.tylingsoft.com/)?
What I need is supporting [mermaidjs](https://mermaidjs.github.io/) and the toolbar for markdown in marp, and I've found another project [vortex](https://github.com/tajpure/vortex) already supporting mermaidjs.

It will be really nice if you could add these.

**Comment by yhatt** [comment]
Essentially MarkdownPlus is a different project, and we have to split issues of feature you want.

In the core of Marp Next, we are considering to support flowchart rendering by mermaid.js. Please track #125.

Toolbar is a duplicate issue of #84. Currently we're not considered about issues for GUI tool in Marp Next because of the order of projects.
