### ISSUE TITLE
Feature request: Make it possible to import new themes

### ISSUE THREAD

**Issue by ghost** [yhatt/marp#5]
At the moment this requires rebuilding the app. It would be great if I could make a theme for my university and upload it somewhere and people could just download and import it.

**Comment by abunsen** [comment]
👍

**Comment by TobLoef** [comment]
Definitely looking forward to this feature :+1:

**Comment by adamprocter** [comment]
Perhaps take a look at the way Ulysses app has created a theme system for export.

**Comment by rtvb** [comment]
I would prefer being able to add a reference to a `.css` file (that I can put next to the `.md` file and any image file). Let's keep things simple.

**Comment by dialex** [comment]
I want this so badly!! It would absolutely destroy Deckset.

**Comment by pascaliske** [comment]
👍🏻

**Comment by Sathors** [comment]
Indeed, a much needed feature.
I support the css file reference, to make things simple.

**Comment by Svenito** [comment]
:+1:  for this too. Pluggable themes would be great. Or simply allowing users to include a custom css alongside their project

**Comment by flashpixx** [comment]
This is a very useful feature, my proposal is a user-definied directory e.g. under Linux ```~/.marp/theme``` and under OSX ```~/Library/Application Support/Marp/theme```. The theme (CSS file) can be stored under this directory and Marp appends the current (default) list with these themes from this directory

**Comment by robsalasco** [comment]
+1

**Comment by brunitto** [comment]
+1

**Comment by kode7** [comment]
+1

**Comment by rakshazi** [comment]
Hello!
Any update on this?
It's really must-have feature. In our company all presentations must be with company's template (color, fonts, images, etc). So we can't use Marp without additional actions (I mean, we build it with our custom theme every time)

**Comment by fredtempez** [comment]
Hi,
just import some [CSS in your markdown and voila.](https://tic-et-net.org/2017/11/30/how-to-change-the-theme-in-marp/)

**Comment by yhatt** [comment]
I'm sorry to have kept you waiting. In order to support much better custom themes, we are develpoing [the next-gen Marp tools](https://github.com/marp-team/) for a long time.

Today, we have released [a CLI interface of the next-gen Marp](https://github.com/marp-team/marp-cli/), that has supported importing the custom theme CSS based on our new [Marpit framework](https://marpit.marp.app/). It is still an early-alpha release, but you can try to create custom theme for new Marp with with live-previewing.

If you have installed [Node](https://nodejs.org/), you can try the command like this:

```bash
npx @marp-team/marp-cli --theme your-theme.css --watch slide.md
```

![](https://user-images.githubusercontent.com/3993388/45731426-81540300-bc12-11e8-84aa-6fcc14ca28af.gif)

[Please refer to the documentation of Marpit](https://marpit.marp.app/theme-css) to learn how to create theme. Marpit has the CSS theming system that can design slides with clean markup.

In future, the planned GUI interfaces at the next-gen Marp, like online version (marp-web) and Desktop version (marp-electron), would become to support custom theme. You can create your custom theme in CLI until these are ready. (coming soon)

**Comment by yhatt** [comment]
We close this issue because theme CSS support for Marp Next tools (based on Marpit framework) is getting stable (#267).
