### ISSUE TITLE
Emoji's not exported to PDF

### ISSUE THREAD

**Issue by neilstuartcraig** [yhatt/marp#57]
Hi all

I just started using Marp and it's excellent - it's replaced PPT already.

I noticed that emoji's aren't exported to PDF though (i tried viewing in preview and Chrome) on both my OSX 10.9 and 10.11 installs. I don't think there's a generic issue with emoji's and PDF as e.g. [this PDF](http://emogi.com/documents/Emoji_Report_2015.pdf) has emoji's.

Happy to help/test/code in any way necessary if you're interested in supporting this.

Cheers
Neil

**Comment by yhatt** [comment]
I also saw it in OSX 10.11. Are you using Apple's emoji? (You'll see emoji image at text buffer if you use it)

We will look for how to resolve. Until we resolve this issue, you can use [Github style syntax](http://www.webpagefx.com/tools/emoji-cheat-sheet/) like `:smile:`.

**Comment by neilstuartcraig** [comment]
Ah cool, thanks. Yes, I was using Apple emojis which don't work for me. Changing to GH emojis does work in the preview and the exported PDF.

**Comment by staticgears** [comment]
Emojis work for us

**Comment by djds23** [comment]
@yhatt as a note, this does not work inside code snippets. 

I use 👈 ☝️ 👇 in code comments for snippets in my slides, and the `:point_up:` syntax is rendered as text, not as the emoji. 

Thank you very much for your work on this product!

**Comment by yhatt** [comment]
We're still keeping to work about emoji problems.

In [the core](https://github.com/marp-team/marp-core) of [Marp Next](https://github.com/marp-team/marp), we support the aggressive conversion of emoji (shortcode and Unicode) into SVG vector images provided by twemoji. It can convert emoji in `<code>` element too. It would be a default behavior of Marp Next because we want to provide immutable exported result in any environments.

The trade-off for using aggressive conversion is not to be possible rendering Unicode emoji by system fonts (e.g. Apple Color Emoji, Segoe UI Emoji). So [Marp Core can disable the agressive conversion](https://github.com/marp-team/marp-core#emoji-object), but it causes issues for each environments.

- Windows: Emoji would not colored in PDF, be outlined. We found a workaround in marp-team/marpit#18, but marp-team/marpit#53 reverts it because of an issue in big font.
- Mac: Apple emoji is not vector image, so the quality of emoji in exported PDF is poor. A workaround for windows will vanish Mac emoji.
