### ISSUE TITLE
Add support to Deckset files

### ISSUE THREAD

**Issue by fpg1503** [yhatt/marp#60]
[Deckset](http://www.decksetapp.com) is a paid app to write slides using markdown. I would like to render my deckset files using Marp.

The missing functionalities are:
# Text
- [ ] `#[fit]` to make the text fit to the slide
# Images
- [ ]  `![fit]` attribute to make images fit the slide
- [ ] Add filter to images when there is more content on screen, use `![original]` to disable it
- [ ] `![original 250%]` to zoom in
- [ ] `![left]` and `![right]` to align images
- [ ] `![filtered]` to force the application of a filter on aligned images
- [ ] `![inline]` to use inline images (current behavior)
# Videos
- [ ] Inline videos
- [ ] Youtube Embedding
- [ ] `left`, `right`, `fit`, `fill` and percentage sizing
- [ ] `autoplay`, `loop` and `mute`
# Presenter notes
- [ ] `^` creates presenter notes
# Footer and slide numbers
- [ ] `footer: My Footer` directive on top of file
- [ ] `slidenumbers: true` directive on top of file
# Links
- [ ] Ability to add link to other slides using `<a>`
# Footnotes and named references
- [ ] `[^1]` to add footnotes
- [ ] `[^Wiles, 1995]` to add named references
# TeX
- [ ] Use `$$` delimiters to determine TeX formulas
# Auto-scaling
- [ ] `autoscale: true` directive on top of file
# Build steps
- [ ] `build-lists: true` directive on top of file

More information about each of this features can be seen on their [cheat sheet](http://www.decksetapp.com/cheatsheet/)

**Comment by yhatt** [comment]
We are making an effort that to be able to have power of expression like a Deckset. However, we don't aim to support complete Deckset syntax. If Marp had supported Deckset file, I think it will implemented by "Import from Deckset".

Especially `slidenumbers: true` already has supported with different syntax `<!-- page_number: true -->` (Marp's page directive). Directives is using HTML comment for compatibility of Markdown syntax because Marp has the side of markdown editor like a Markdown view mode.

And the future version `v0.0.9pre` also has several functions: Footer, Background images, and TeX support.

**Comment by alperyilmaz** [comment]
Hopefully Marp turns out to be as better as Deckset..

**Comment by wookayin** [comment]
+1, especially for the #[fit] teature

**Comment by Keleir** [comment]
Also wanted the `Zoom in` feature to make a image full of a slide page. 👍
