### ISSUE TITLE
Multi column pages, feature request.

### ISSUE THREAD

**Issue by seperman** [yhatt/marp#82]
Hello,

I know markdown doesn't let you have multi columns. And the markdown tables can't show code blocks. Can Marp do it?

Thanks

**Comment by garnierclement** [comment]
Hi, I agree with superman. Indeed it would be a great additional feature, especially for widescreen slides 16/9. As we separate slides with `---` maybe we could simply separate columns with `|||` ? Just a suggestion here but it would be very useful.

**Comment by DoktorMike** [comment]
I agree it would be superuseful for me as I depend on these two column layouts for many presentations. :) In RMarkdown I usually add a html snippet that does the trick. Maybe that trick would work fine for Marp too?

**Comment by yhatt** [comment]
We're making a clean sweep of piled up issues.

Currently we are working [the next Marp](https://github.com/marp-team/marp) in [marp-team](https://github.com/marp-team). But we have not planned to add another syntax for supporting multi columns like `|||` because it would be against CommonMark. See also #87.

As an alternative, we added [the example of multi-column support](https://marpit.marp.app/usage?id=extend-marpit-by-plugins) in [Marpit](https://marpit.marp.app), the base framework of Marp Next, with extended by plugins. In fact, the multi-column layout has supported in [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Using_multi-column_layouts).
