### ISSUE TITLE
Markdown renderer

### ISSUE THREAD

**Issue by noraj** [yhatt/marp#87]
Hi Yuki,

I love your project this is pretty amazing and usefull

BUT the markdown renderer/parser you use doesn't respect markdown syntax at all.

There is a lot of examples with list, quotes, line feed etc ...

You can tests examples of syntax from the original markdown:
https://daringfireball.net/projects/markdown/syntax

That would be great if your replace the renderer you actually use with one implementing all markdown features + Github Flavored Markdown ones.

There is a lot of markdown renderer / parser that won't be a problem.

**Comment by honzajavorek** [comment]
http://commonmark.org/ ?

**Comment by noraj1337** [comment]
@honzajavorek : what do you suggest ?

**Comment by honzajavorek** [comment]
@noraj1337 The problem with the original Markdown "spec" is that it insufficiently describes all corner cases of Markdown parsing. That's why CommonMark was created as a way to standardize around some kind of community-maintained spec.

So,

1. If marp already uses CommonMark (I didn't check) and your issues are that the CommonMark-spec-compilant parser works in a different way than you would expect from the original Markdown spec, then I'd suggest to stick to CommonMark anyway, as it's currently the only sane way to support Markdown today and in the near future, with expectable results.

2. If marp doesn't use CommonMark yet, then I suggest to migrate to it and use CommonMark-spec-compilant parser, which should avoid any future issues like this.

**Comment by noraj1337** [comment]
@honzajavorek : Yeah you're right, and commonMark is really good initiative but it does support only original markdown. For example array (from GMF) are quite useful and used everywhere but not supported by commonMark.

Here is what GMF add more : https://help.github.com/enterprise/11.10.340/user/articles/github-flavored-markdown/

And here is github parser : https://github.com/github/markup

I don't if it possible to use commonMark + GMF features.

But there is a lot of others additions (https://github.com/jgm/CommonMark/wiki/Markdown-Flavors).

**Comment by yhatt** [comment]
It has already resolved in Marp Next. It has grown durable against a practical use, so we close this issue.

## Details

yhatt/marp had already used [markdown-it](https://github.com/markdown-it/markdown-it), the 100% CommonMark compliant parser. But I had not used CommonMark option in constructor option.  So we had decided to strictly respect CommonMark (0.28) by default in [Marpit](https://github.com/marp-team/marpit), the brand-new framework of Marp Next ecosystem (#267).

Additional syntax never breaks CommonMark document. And we will hate extra syntax to require breaking CommonMark. (But power user can extend favorite syntax by [markdown-it plugin](https://www.npmjs.com/search?q=keywords:markdown-it-plugin).)

[Our new core](https://github.com/marp-team/marp-core) based on Marpit has *carefully selected* extra syntaxes: GFM table, Pandoc style math typesetting, and emoji shorthand.

**Comment by noraj** [comment]
@yhatt Yeah respecting CommonMark is a good idea. I didn't use Marp Next but I read the new idea of the project and it just looks amazing. I'm didn't write slides since a lot of times but I'll sure use Marp when I'll do.
